"""
Natural-language query engine.

Design choice (this is the core "LLM integration" of the system):
the LLM is NEVER asked to generate pandas/SQL code that gets executed.
Instead it is asked to translate the question into a small, constrained
JSON "query plan" (filters + optional group-by + optional metric). That
plan is validated against a whitelist of columns/operators/aggregations
and executed with plain pandas. This avoids prompt-injection-to-code-
execution risk entirely while still giving the LLM full flexibility to
interpret free-form questions.

The final natural-language answer is generated by a small deterministic
template from the *executed result*, not by asking the LLM to also
free-write the number (which risks hallucinated figures). The LLM's job
is understanding the question, not reporting the number.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

import pandas as pd

from app.data_layer import load_tickets, dataset_now, schema_prompt_block
from app.llm_client import complete_json, LLMResponseError

ALLOWED_COLUMNS = {
    "category", "priority", "status", "agent_id",
    "response_time_hrs", "resolution_time_hrs", "customer_rating",
    "age_hours", "is_unresolved", "created_at",
}
ALLOWED_FILTER_OPS = {"eq", "neq", "gt", "gte", "lt", "lte", "in", "contains"}
ALLOWED_AGGS = {"count", "mean", "sum", "min", "max", "median"}

SYSTEM_PROMPT = f"""You translate a user's question about a customer-support ticket \
dataset into a strict JSON query plan. You do not answer the question yourself \
and you do not write code — you only produce the JSON plan described below.

Dataset columns you may reference:
{schema_prompt_block()}

Return ONLY a JSON object with this shape (omit keys you don't need):
{{
  "filters": [{{"column": "<col>", "op": "<eq|neq|gt|gte|lt|lte|in|contains>", "value": <value>}}],
  "time_window_days": <int, optional — e.g. 7 for "this week", 1 for "today", 30 for "this month">,
  "groupby": "<column, optional>",
  "metric": {{"column": "<col or 'ticket_id' for row counts>", "agg": "<count|mean|sum|min|max|median>"}},
  "sort_ascending": <true|false, optional — for 'lowest'/'highest' style questions>,
  "limit": <int, optional — for 'top N' or when listing individual tickets>,
  "intent": "<aggregate|groupby_agg|list>"
}}

Rules:
- "intent" is required: "aggregate" for a single number (e.g. "how many", "average X"),
  "groupby_agg" when the question compares across a category/agent/priority/status
  (e.g. "which agent has the lowest rating", "average rating by category"),
  "list" when the user wants to see individual matching tickets.
- Only use columns and ops from the lists above. Never invent a column.
- For "lowest"/"highest"/"most"/"least" questions, use groupby_agg with sort_ascending
  and limit set appropriately (e.g. limit=1 for "which agent has the lowest ...").
- For yes/no or "are there any" questions about anomalies, do NOT try to answer here —
  that is handled by a separate anomaly-detection system, not this query planner.
- "Unresolved" means status is 'Open' or 'Escalated'; you may express this as a filter
  on "is_unresolved" with op "eq" and value true, OR as a status "in" filter.
- If the question is genuinely unanswerable from these columns, return
  {{"intent": "unsupported", "reason": "<short reason>"}}.
- Respond with ONLY the JSON object. No prose, no markdown fences.
"""


@dataclass
class QueryPlan:
    intent: str
    filters: list[dict] = field(default_factory=list)
    time_window_days: Optional[int] = None
    groupby: Optional[str] = None
    metric: Optional[dict] = None
    sort_ascending: Optional[bool] = None
    limit: Optional[int] = None
    reason: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict) -> "QueryPlan":
        return cls(
            intent=d.get("intent", "aggregate"),
            filters=d.get("filters") or [],
            time_window_days=d.get("time_window_days"),
            groupby=d.get("groupby"),
            metric=d.get("metric"),
            sort_ascending=d.get("sort_ascending"),
            limit=d.get("limit"),
            reason=d.get("reason"),
        )


class PlanValidationError(ValueError):
    pass


def get_query_plan(question: str) -> QueryPlan:
    """Ask the LLM to translate `question` into a validated QueryPlan."""
    raw = complete_json(SYSTEM_PROMPT, question)
    plan = QueryPlan.from_dict(raw)
    _validate_plan(plan)
    return plan


def _validate_plan(plan: QueryPlan) -> None:
    if plan.intent == "unsupported":
        return
    if plan.intent not in {"aggregate", "groupby_agg", "list"}:
        raise PlanValidationError(f"Unknown intent: {plan.intent}")
    for f in plan.filters:
        col, op = f.get("column"), f.get("op")
        if col not in ALLOWED_COLUMNS:
            raise PlanValidationError(f"Filter references disallowed column: {col}")
        if op not in ALLOWED_FILTER_OPS:
            raise PlanValidationError(f"Filter uses disallowed operator: {op}")
    if plan.groupby is not None and plan.groupby not in ALLOWED_COLUMNS:
        raise PlanValidationError(f"Groupby references disallowed column: {plan.groupby}")
    if plan.metric is not None:
        mcol, magg = plan.metric.get("column"), plan.metric.get("agg")
        if mcol not in ALLOWED_COLUMNS | {"ticket_id"}:
            raise PlanValidationError(f"Metric references disallowed column: {mcol}")
        if magg not in ALLOWED_AGGS:
            raise PlanValidationError(f"Metric uses disallowed aggregation: {magg}")


def _apply_filters(df: pd.DataFrame, filters: list[dict]) -> pd.DataFrame:
    for f in filters:
        col, op, val = f["column"], f["op"], f.get("value")
        series = df[col]
        if op == "eq":
            df = df[series == val]
        elif op == "neq":
            df = df[series != val]
        elif op == "gt":
            df = df[series > val]
        elif op == "gte":
            df = df[series >= val]
        elif op == "lt":
            df = df[series < val]
        elif op == "lte":
            df = df[series <= val]
        elif op == "in":
            vals = val if isinstance(val, list) else [val]
            df = df[series.isin(vals)]
        elif op == "contains":
            df = df[series.astype(str).str.contains(str(val), case=False, na=False)]
    return df


def execute_plan(plan: QueryPlan) -> dict[str, Any]:
    """Run a validated QueryPlan against the dataset and return a result payload."""
    if plan.intent == "unsupported":
        return {"intent": "unsupported", "reason": plan.reason or "Question is out of scope for this dataset."}

    df = load_tickets()

    if plan.time_window_days:
        cutoff = dataset_now() - pd.Timedelta(days=plan.time_window_days)
        df = df[df["created_at"] >= cutoff]

    df = _apply_filters(df, plan.filters)
    matched_count = len(df)

    if plan.intent == "list":
        limit = plan.limit or 20
        cols = [
            "ticket_id", "created_at", "category", "priority", "status",
            "response_time_hrs", "resolution_time_hrs", "agent_id",
            "customer_rating", "issue_summary",
        ]
        rows = df[cols].head(limit).copy()
        rows["created_at"] = rows["created_at"].astype(str)
        rows = rows.astype(object).where(pd.notnull(rows), None)
        return {
            "intent": "list",
            "matched_count": matched_count,
            "returned_count": len(rows),
            "rows": rows.to_dict(orient="records"),
        }

    if plan.intent == "aggregate":
        if plan.metric is None:
            value = matched_count
            agg_desc = "count"
        else:
            mcol, magg = plan.metric["column"], plan.metric["agg"]
            if magg == "count" or mcol == "ticket_id":
                value = matched_count
            else:
                value = getattr(df[mcol], magg)()
                value = None if pd.isna(value) else round(float(value), 3)
            agg_desc = f"{magg}({mcol})"
        return {"intent": "aggregate", "matched_count": matched_count, "metric": agg_desc, "value": value}

    if plan.intent == "groupby_agg":
        group_col = plan.groupby or "agent_id"
        if plan.metric is None:
            grouped = df.groupby(group_col).size().rename("value")
        else:
            mcol, magg = plan.metric["column"], plan.metric["agg"]
            if magg == "count" or mcol == "ticket_id":
                grouped = df.groupby(group_col).size().rename("value")
            else:
                grouped = df.groupby(group_col)[mcol].agg(magg).rename("value")
        grouped = grouped.sort_values(ascending=bool(plan.sort_ascending)) if plan.sort_ascending is not None \
            else grouped.sort_values(ascending=False)
        if plan.limit:
            grouped = grouped.head(plan.limit)
        result = [
            {"group": str(idx), "value": (None if pd.isna(v) else round(float(v), 3))}
            for idx, v in grouped.items()
        ]
        return {
            "intent": "groupby_agg",
            "matched_count": matched_count,
            "groupby": group_col,
            "metric": (f"{plan.metric['agg']}({plan.metric['column']})" if plan.metric else "count"),
            "results": result,
        }

    raise PlanValidationError(f"Unhandled intent: {plan.intent}")


def render_answer(question: str, result: dict) -> str:
    """Turn an execution result into a short natural-language answer."""
    intent = result["intent"]
    if intent == "unsupported":
        return f"I can't answer that from this dataset: {result['reason']}"
    if intent == "aggregate":
        if result["value"] is None:
            return "No matching tickets have data for that metric."
        return f"{result['metric']} over {result['matched_count']} matching ticket(s) = {result['value']}"
    if intent == "list":
        return (
            f"Found {result['matched_count']} matching ticket(s); "
            f"showing {result['returned_count']}."
        )
    if intent == "groupby_agg":
        if not result["results"]:
            return "No matching tickets to group."
        top = result["results"][0]
        return (
            f"By {result['groupby']}, top result: {top['group']} = {top['value']} "
            f"({result['metric']}). {len(result['results'])} group(s) returned."
        )
    return "Unrecognized result shape."


def answer_question(question: str) -> dict[str, Any]:
    """End-to-end: question -> LLM plan -> validated -> executed -> answer."""
    try:
        plan = get_query_plan(question)
    except LLMResponseError as exc:
        return {"question": question, "error": f"Could not interpret the question: {exc}"}
    except Exception as exc:  # LLM backend not configured, network error, etc.
        return {"question": question, "error": str(exc)}

    try:
        result = execute_plan(plan)
    except PlanValidationError as exc:
        return {"question": question, "error": f"Generated query plan was invalid: {exc}", "plan": plan.__dict__}

    return {
        "question": question,
        "plan": plan.__dict__,
        "result": result,
        "answer": render_answer(question, result),
    }
